### ISSUE TITLE
force HTTPS

### ISSUE THREAD

**Issue by dabernathy89** [dabernathy89/longhorn-php-website#2]
can this be done at the Cloudflare level?

**Comment by iansltx** [comment]
It can. Crypto tab. There's an option for HSTS there. Just turned it on for some other site of mine.

**Comment by dabernathy89** [comment]
We should be careful about HSTS though, because if we ever move away from Github pages we may want it (at least temporarily) available over HTTP right?

**Comment by iansltx** [comment]
That's the risk. But we're putting this behind Cloudflare so that's what's terminating our SSL anyway. And LetsEncrypt is a thing, so i wouldn't be too concerned about the downsides of throwing HSTS in there with a longish TTL, given that's the only way I'm seeing to enforce SSL at Cloudflare's level (vs. if we had nginx backing this, in which case a 302 http -> https would be trivial).

**Comment by dabernathy89** [comment]
@llbbl can we do this at Cloudflare?

**Comment by llbbl** [comment]
@dabernathy89 yes we can
